# Start Status bar
# exec-once = ~/.config/waybar/launch.sh
# exec-once = sleep 1 && hyprpanel
exec-once = qs -c noctalia-shell

# Using hypridle to start hyprlock
exec-once = hypridle

# relaod plugins
# exec-once = hyprpm reload

# Start network manager applet: very important
exec-once = nm-applet --indicator

# Start blueman (bluetooth manager) 
exec-once = blueman-applet

# Start wallpaper backend
exec-once = awww-daemon

# Load Notification Daemon
# exec-once = swaync

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Setup XDG for screen sharing and start waypaper and waybar
# exec-once = ~/.config/hypr/scripts/xdg.sh

# Start Polkit
# exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Wallpaper
# exec-once = ~/.config/hypr/scripts/wallpaper-restore.sh

# Load GTK settings
# exec-once = ~/.config/hypr/scripts/gtk.sh
